apiVersion: v1
kind: ConfigMap
metadata:
  name: kps-config
  namespace: {{ .Release.Namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
      external_labels:
        source: kps-zeroexposure
        node: "$NODE_NAME"

    remote_write:
      - url: {{ .Values.remoteWriteUrl | quote }}

    scrape_configs:

      - job_name: "etcd-local"
        static_configs:
          - targets: ["127.0.0.1:2381"]
        relabel_configs:
          - target_label: source
            replacement: kps-zeroexposure

      - job_name: "kube-proxy-local"
        static_configs:
          - targets: ["127.0.0.1:10249"]
        relabel_configs:
          - target_label: source
            replacement: kps-zeroexposure

      - job_name: "controller-manager-local"
        scheme: https
        static_configs:
          - targets: ["127.0.0.1:10257"]
        tls_config:
          ca_file: /etc/pki/ca.crt
          cert_file: /etc/pki/apiserver-kubelet-client.crt
          key_file: /etc/pki/apiserver-kubelet-client.key
          insecure_skip_verify: true
        relabel_configs:
          - target_label: source
            replacement: kps-zeroexposure

      - job_name: "scheduler-local"
        scheme: https
        static_configs:
          - targets: ["127.0.0.1:10259"]
        tls_config:
          ca_file: /etc/pki/ca.crt
          cert_file: /etc/pki/apiserver-kubelet-client.crt
          key_file: /etc/pki/apiserver-kubelet-client.key
          insecure_skip_verify: true
        relabel_configs:
          - target_label: source
            replacement: kps-zeroexposure
